#!/usr/bin/env bash
set -euo pipefail

# check-budget.sh — Check monthly auto-fix spend against budget thresholds.
# Creates GitHub Issues (with dedup) when thresholds are crossed.
#
# Required env vars:
#   GH_TOKEN      — for gh issue commands
#   CENTRAL_REPO  — "fbetancourtc/auto-fix-agent" (where issues are created)

PRICING_FILE="_auto-fix-scripts/config/pricing.json"
METRICS_FILE="_auto-fix-scripts/metrics/runs.json"

MONTHLY_BUDGET=$(jq -r '.budget.monthly_limit_usd' "$PRICING_FILE")
CURRENT_MONTH=$(date -u +%Y-%m)
TOTAL_COST=$(jq "[.runs[] | select(.month == \"$CURRENT_MONTH\") | .cost_usd] | add // 0" "$METRICS_FILE")

PCT=$(echo "$TOTAL_COST $MONTHLY_BUDGET" | awk '{printf "%.0f", ($1/$2)*100}')

echo "Monthly spend: \$$TOTAL_COST / \$$MONTHLY_BUDGET (${PCT}%)"

# Check each threshold from config
for THRESHOLD in $(jq -r '.budget.alert_thresholds_pct[]' "$PRICING_FILE"); do
  if [ "$PCT" -ge "$THRESHOLD" ]; then
    # Dedup: check if alert already exists for this threshold + month
    EXISTING=$(gh issue list --repo "$CENTRAL_REPO" --label "budget-alert" \
      --search "Budget ${THRESHOLD}% ${CURRENT_MONTH}" \
      --json number --jq '.[0].number' 2>/dev/null || true)

    if [ -z "$EXISTING" ] || [ "$EXISTING" = "null" ]; then
      ACTION_MSG="No action required yet. Monitor spending."
      if [ "$THRESHOLD" -ge 100 ]; then
        ACTION_MSG="Auto-fix continues running. Review spending and decide whether to pause."
      fi

      gh issue create --repo "$CENTRAL_REPO" \
        --title "Budget ${THRESHOLD}% alert - ${CURRENT_MONTH}" \
        --label "budget-alert" \
        --body "Monthly auto-fix spend has reached **${THRESHOLD}%** (\$${TOTAL_COST} of \$${MONTHLY_BUDGET}).

## Details
- Month: ${CURRENT_MONTH}
- Total cost: \$${TOTAL_COST}
- Budget: \$${MONTHLY_BUDGET}
- Threshold: ${THRESHOLD}%

## Action
${ACTION_MSG}

---
*Generated by [auto-fix-agent](https://github.com/fbetancourtc/auto-fix-agent) budget monitor*"
      echo "Created budget alert for ${THRESHOLD}% threshold"
    else
      echo "Budget alert for ${THRESHOLD}% already exists (issue #${EXISTING}), skipping"
    fi
  fi
done
